/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRegisterLoginRouteImport } from './routes/_layoutRegisterLogin'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutRegisterLoginRegisterRouteImport } from './routes/_layoutRegisterLogin.register'
import { Route as LayoutRegisterLoginLoginRouteImport } from './routes/_layoutRegisterLogin.login'
import { Route as LayoutDashboardRouteImport } from './routes/_layout.dashboard'

const LayoutRegisterLoginRoute = LayoutRegisterLoginRouteImport.update({
  id: '/_layoutRegisterLogin',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRegisterLoginRegisterRoute =
  LayoutRegisterLoginRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => LayoutRegisterLoginRoute,
  } as any)
const LayoutRegisterLoginLoginRoute =
  LayoutRegisterLoginLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => LayoutRegisterLoginRoute,
  } as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/login': typeof LayoutRegisterLoginLoginRoute
  '/register': typeof LayoutRegisterLoginRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/login': typeof LayoutRegisterLoginLoginRoute
  '/register': typeof LayoutRegisterLoginRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layoutRegisterLogin': typeof LayoutRegisterLoginRouteWithChildren
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layoutRegisterLogin/login': typeof LayoutRegisterLoginLoginRoute
  '/_layoutRegisterLogin/register': typeof LayoutRegisterLoginRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/login' | '/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/login' | '/register'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layoutRegisterLogin'
    | '/_layout/dashboard'
    | '/_layoutRegisterLogin/login'
    | '/_layoutRegisterLogin/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LayoutRegisterLoginRoute: typeof LayoutRegisterLoginRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layoutRegisterLogin': {
      id: '/_layoutRegisterLogin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRegisterLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layoutRegisterLogin/register': {
      id: '/_layoutRegisterLogin/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof LayoutRegisterLoginRegisterRouteImport
      parentRoute: typeof LayoutRegisterLoginRoute
    }
    '/_layoutRegisterLogin/login': {
      id: '/_layoutRegisterLogin/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutRegisterLoginLoginRouteImport
      parentRoute: typeof LayoutRegisterLoginRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutDashboardRoute: typeof LayoutDashboardRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDashboardRoute: LayoutDashboardRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface LayoutRegisterLoginRouteChildren {
  LayoutRegisterLoginLoginRoute: typeof LayoutRegisterLoginLoginRoute
  LayoutRegisterLoginRegisterRoute: typeof LayoutRegisterLoginRegisterRoute
}

const LayoutRegisterLoginRouteChildren: LayoutRegisterLoginRouteChildren = {
  LayoutRegisterLoginLoginRoute: LayoutRegisterLoginLoginRoute,
  LayoutRegisterLoginRegisterRoute: LayoutRegisterLoginRegisterRoute,
}

const LayoutRegisterLoginRouteWithChildren =
  LayoutRegisterLoginRoute._addFileChildren(LayoutRegisterLoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LayoutRegisterLoginRoute: LayoutRegisterLoginRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
