/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRegisterLoginRouteImport } from './routes/_layoutRegisterLogin'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutRegisterLoginRegisterRouteImport } from './routes/_layoutRegisterLogin.register'
import { Route as LayoutRegisterLoginLoginRouteImport } from './routes/_layoutRegisterLogin.login'
import { Route as LayoutUsersRouteImport } from './routes/_layout.users'
import { Route as LayoutParametresRouteImport } from './routes/_layout.parametres'
import { Route as LayoutOrganisationsRouteImport } from './routes/_layout.organisations'
import { Route as LayoutLicencesRouteImport } from './routes/_layout.licences'
import { Route as LayoutEquipementsRouteImport } from './routes/_layout.equipements'
import { Route as LayoutDashboardRouteImport } from './routes/_layout.dashboard'
import { Route as LayoutAffectationsRouteImport } from './routes/_layout.affectations'
import { Route as LayoutRapportsLicencesExpirantesRouteImport } from './routes/_layout.rapports.licences-expirantes'
import { Route as LayoutRapportsInventaireRouteImport } from './routes/_layout.rapports.inventaire'

const LayoutRegisterLoginRoute = LayoutRegisterLoginRouteImport.update({
  id: '/_layoutRegisterLogin',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRegisterLoginRegisterRoute =
  LayoutRegisterLoginRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => LayoutRegisterLoginRoute,
  } as any)
const LayoutRegisterLoginLoginRoute =
  LayoutRegisterLoginLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => LayoutRegisterLoginRoute,
  } as any)
const LayoutUsersRoute = LayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutParametresRoute = LayoutParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrganisationsRoute = LayoutOrganisationsRouteImport.update({
  id: '/organisations',
  path: '/organisations',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLicencesRoute = LayoutLicencesRouteImport.update({
  id: '/licences',
  path: '/licences',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEquipementsRoute = LayoutEquipementsRouteImport.update({
  id: '/equipements',
  path: '/equipements',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAffectationsRoute = LayoutAffectationsRouteImport.update({
  id: '/affectations',
  path: '/affectations',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRapportsLicencesExpirantesRoute =
  LayoutRapportsLicencesExpirantesRouteImport.update({
    id: '/rapports/licences-expirantes',
    path: '/rapports/licences-expirantes',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutRapportsInventaireRoute =
  LayoutRapportsInventaireRouteImport.update({
    id: '/rapports/inventaire',
    path: '/rapports/inventaire',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affectations': typeof LayoutAffectationsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/equipements': typeof LayoutEquipementsRoute
  '/licences': typeof LayoutLicencesRoute
  '/organisations': typeof LayoutOrganisationsRoute
  '/parametres': typeof LayoutParametresRoute
  '/users': typeof LayoutUsersRoute
  '/login': typeof LayoutRegisterLoginLoginRoute
  '/register': typeof LayoutRegisterLoginRegisterRoute
  '/rapports/inventaire': typeof LayoutRapportsInventaireRoute
  '/rapports/licences-expirantes': typeof LayoutRapportsLicencesExpirantesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affectations': typeof LayoutAffectationsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/equipements': typeof LayoutEquipementsRoute
  '/licences': typeof LayoutLicencesRoute
  '/organisations': typeof LayoutOrganisationsRoute
  '/parametres': typeof LayoutParametresRoute
  '/users': typeof LayoutUsersRoute
  '/login': typeof LayoutRegisterLoginLoginRoute
  '/register': typeof LayoutRegisterLoginRegisterRoute
  '/rapports/inventaire': typeof LayoutRapportsInventaireRoute
  '/rapports/licences-expirantes': typeof LayoutRapportsLicencesExpirantesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layoutRegisterLogin': typeof LayoutRegisterLoginRouteWithChildren
  '/_layout/affectations': typeof LayoutAffectationsRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/equipements': typeof LayoutEquipementsRoute
  '/_layout/licences': typeof LayoutLicencesRoute
  '/_layout/organisations': typeof LayoutOrganisationsRoute
  '/_layout/parametres': typeof LayoutParametresRoute
  '/_layout/users': typeof LayoutUsersRoute
  '/_layoutRegisterLogin/login': typeof LayoutRegisterLoginLoginRoute
  '/_layoutRegisterLogin/register': typeof LayoutRegisterLoginRegisterRoute
  '/_layout/rapports/inventaire': typeof LayoutRapportsInventaireRoute
  '/_layout/rapports/licences-expirantes': typeof LayoutRapportsLicencesExpirantesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affectations'
    | '/dashboard'
    | '/equipements'
    | '/licences'
    | '/organisations'
    | '/parametres'
    | '/users'
    | '/login'
    | '/register'
    | '/rapports/inventaire'
    | '/rapports/licences-expirantes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affectations'
    | '/dashboard'
    | '/equipements'
    | '/licences'
    | '/organisations'
    | '/parametres'
    | '/users'
    | '/login'
    | '/register'
    | '/rapports/inventaire'
    | '/rapports/licences-expirantes'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layoutRegisterLogin'
    | '/_layout/affectations'
    | '/_layout/dashboard'
    | '/_layout/equipements'
    | '/_layout/licences'
    | '/_layout/organisations'
    | '/_layout/parametres'
    | '/_layout/users'
    | '/_layoutRegisterLogin/login'
    | '/_layoutRegisterLogin/register'
    | '/_layout/rapports/inventaire'
    | '/_layout/rapports/licences-expirantes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LayoutRegisterLoginRoute: typeof LayoutRegisterLoginRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layoutRegisterLogin': {
      id: '/_layoutRegisterLogin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRegisterLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layoutRegisterLogin/register': {
      id: '/_layoutRegisterLogin/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof LayoutRegisterLoginRegisterRouteImport
      parentRoute: typeof LayoutRegisterLoginRoute
    }
    '/_layoutRegisterLogin/login': {
      id: '/_layoutRegisterLogin/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutRegisterLoginLoginRouteImport
      parentRoute: typeof LayoutRegisterLoginRoute
    }
    '/_layout/users': {
      id: '/_layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/parametres': {
      id: '/_layout/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof LayoutParametresRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/organisations': {
      id: '/_layout/organisations'
      path: '/organisations'
      fullPath: '/organisations'
      preLoaderRoute: typeof LayoutOrganisationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/licences': {
      id: '/_layout/licences'
      path: '/licences'
      fullPath: '/licences'
      preLoaderRoute: typeof LayoutLicencesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/equipements': {
      id: '/_layout/equipements'
      path: '/equipements'
      fullPath: '/equipements'
      preLoaderRoute: typeof LayoutEquipementsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/affectations': {
      id: '/_layout/affectations'
      path: '/affectations'
      fullPath: '/affectations'
      preLoaderRoute: typeof LayoutAffectationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rapports/licences-expirantes': {
      id: '/_layout/rapports/licences-expirantes'
      path: '/rapports/licences-expirantes'
      fullPath: '/rapports/licences-expirantes'
      preLoaderRoute: typeof LayoutRapportsLicencesExpirantesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rapports/inventaire': {
      id: '/_layout/rapports/inventaire'
      path: '/rapports/inventaire'
      fullPath: '/rapports/inventaire'
      preLoaderRoute: typeof LayoutRapportsInventaireRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAffectationsRoute: typeof LayoutAffectationsRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutEquipementsRoute: typeof LayoutEquipementsRoute
  LayoutLicencesRoute: typeof LayoutLicencesRoute
  LayoutOrganisationsRoute: typeof LayoutOrganisationsRoute
  LayoutParametresRoute: typeof LayoutParametresRoute
  LayoutUsersRoute: typeof LayoutUsersRoute
  LayoutRapportsInventaireRoute: typeof LayoutRapportsInventaireRoute
  LayoutRapportsLicencesExpirantesRoute: typeof LayoutRapportsLicencesExpirantesRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAffectationsRoute: LayoutAffectationsRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutEquipementsRoute: LayoutEquipementsRoute,
  LayoutLicencesRoute: LayoutLicencesRoute,
  LayoutOrganisationsRoute: LayoutOrganisationsRoute,
  LayoutParametresRoute: LayoutParametresRoute,
  LayoutUsersRoute: LayoutUsersRoute,
  LayoutRapportsInventaireRoute: LayoutRapportsInventaireRoute,
  LayoutRapportsLicencesExpirantesRoute: LayoutRapportsLicencesExpirantesRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface LayoutRegisterLoginRouteChildren {
  LayoutRegisterLoginLoginRoute: typeof LayoutRegisterLoginLoginRoute
  LayoutRegisterLoginRegisterRoute: typeof LayoutRegisterLoginRegisterRoute
}

const LayoutRegisterLoginRouteChildren: LayoutRegisterLoginRouteChildren = {
  LayoutRegisterLoginLoginRoute: LayoutRegisterLoginLoginRoute,
  LayoutRegisterLoginRegisterRoute: LayoutRegisterLoginRegisterRoute,
}

const LayoutRegisterLoginRouteWithChildren =
  LayoutRegisterLoginRoute._addFileChildren(LayoutRegisterLoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LayoutRegisterLoginRoute: LayoutRegisterLoginRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
